In [2]:
import numpy as np

In [3]:
#Making a single neural

inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1.0]
bias = 2

output = sum(list(x*y for (x,y) in zip(inputs,weights))) + bias
print(output)
print(np.dot(weights,inputs)+bias)

4.8
4.8


In [4]:
# Making a layer of three neurals ---
input = np.array([1,2,3,2.5])

weight = np.array([
    [0.2,0.8,-0.5,1.0],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
])

biases = np.array([2,3,0.5])


output = np.dot(weight,input)+biases
print(output)

[4.8   1.21  2.385]


In [5]:
#now if we have different inputs for different neurals -- 
input2 = np.array([
    [1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]
])

weight2 = np.array([
    [0.2,0.8,-0.5,1.0],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
])

biases2 = np.array([2,3,0.5])

output2 = np.dot(input2,weight2.T) + biases2
output2

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [7]:
#let's say after it we have layer3 for which output of layer2 acts as input --
weight3 = np.array([
    [0.1,-0.14,0.5],
    [-0.5,0.12,-0.33],
    [-0.44,0.73,-0.13]
])

biases3 = np.array([-1,2,-0.5])

layer3_output = np.dot(output2,weight3.T) + biases3
layer3_output

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

In [10]:
#in machine learning input data is mainly represented as X --
np.random.seed(0)

X = np.array([
    [1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]
])

#Now THE GREAT OOPS comes into picture for first time
#today first time it's being used let's explore what effect it puts so it is reputed so much

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons) -> None:
        #here notice the shape of weights if we take this shape we don't need to take a transpose every time
        self.weights = 0.1 * np.random.randn(n_inputs,n_neurons)  #multiplication of 0.1 to handle values greater than 1
        self.biases = np.zeros((1,n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs,self.weights) + self.biases


layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)


layer1.forward(X)
print(layer1.output)

layer2.forward(layer1.output)
print(layer2.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [ ]:
#introducing activation functions ----
#using relu function --

#making a class for relu function ---

class activation_RELU:
    def forward(self,input):
        self.ouput = np.maximum(self.input,0)

for i in input:
    output.append(max(0,i))

