In [1]:
import numpy as np


In [2]:
#creating arrays--
mylist = [1,2,3,4,5]
arr = np.array(mylist)
arr

array([1, 2, 3, 4, 5])

In [3]:
x = np.array(arr)
x

array([1, 2, 3, 4, 5])

In [4]:
#creating multidimensional arrays--
square = [
    [1,1],
    [2,4],
    [3,9],
    [4,16]
]

sq_arr = np.array(square)
print(sq_arr)


[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [5]:
#arange function
#just like range function here we get an array
np.arange(0,11)



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [7]:
arr = np.array(list(i for i in range(0,10)))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
#zeros and ones method--
zero = np.zeros(10)
print(zero)
one = np.ones([3,3])
print(one)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
#eye method to make diagonal matrix--
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
#reshape function--
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr.reshape(3,4)    #this gives error   

ValueError: cannot reshape array of size 9 into shape (3,4)

In [ ]:
arr.reshape(3,)

ValueError: cannot reshape array of size 9 into shape (3,)

In [14]:
arr.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#linespace function--
np.linspace(0,7,10)     #generate 10 evenly separeted values b/w 0 and 7


array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [ ]:
#resize function--
x=np.array(list(i for i in range(10)))
x.reshape(2,5)      #it doesn't change inplace
print(x)

x.resize(2,5)      #it changes inplace
print(x)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:
#generating some random numbers--
a = np.random.rand(3,2) #b/w zero and one we are going to get all the numbers
#here mean is 0 and standard deviation is 1

print(a.mean())
print(a.std())

0.360563971123596
0.21239617624731738


In [ ]:
a = np.random.randn(3,3)    #it is standard normal distribution

a

array([[-0.5810622 ,  1.39832738,  0.27304608],
       [ 0.65081224, -0.08498084, -0.22979168],
       [ 0.09786029,  0.26224013,  1.69420175]])

In [ ]:
np.random.randint(4,15,10)  #10 integers b/w 4 and 15 

array([ 4,  9, 14, 11,  8, 13,  7,  6, 13, 13])

In [ ]:
np.random.randint(0,10,(2,5))

array([[9, 8, 6, 4, 6],
       [9, 8, 5, 3, 7]])

In [ ]:
#INDEXING AND SLICING--
mn = np.random.randint(4,15,10)
mn

array([ 6, 10,  9, 11,  7,  9, 10, 10, 12,  6])

In [ ]:
print(mn[1])
print(mn[0:4])
print(mn[-1])
print(mn[-4:])

10
[ 6 10  9 11]
6
[10 10 12  6]


In [ ]:
print(mn[2:1])

[]


In [ ]:
grid = np.array(list(i for i in range(1,26)))
grid.resize(5,5)
print(grid)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
grid[1,2]

8

In [ ]:
grid[1,1:4]

array([7, 8, 9])

In [ ]:
grid[1:3,2]

array([ 8, 13])

In [ ]:
#conditional indexing--
mn[mn>10]

array([11, 12])

In [ ]:
grid[grid>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
#broadcasting
#suppose we want to change every number greater than 10 to 10
grid[grid>10]=10
grid


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
mn1 = mn.copy()
mn1

array([ 6, 10,  9, 11,  7,  9, 10, 10, 12,  6])

In [ ]:
grid_copy = grid.copy()
grid_copy

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
arr1 = np.random.rand(12)
arr2 = np.random.rand(12)
#to find the common values v/w the given 1 d arrays
np.intersect1d(arr1,arr2)

array([], dtype=float64)

In [ ]:
np.sort(arr1)
arr1

array([0.95353925, 0.0468146 , 0.30777056, 0.64505881, 0.92550596,
       0.73571161, 0.77151191, 0.17588458, 0.8888367 , 0.0856637 ,
       0.13624451, 0.1640397 ])

In [ ]:
#concatinating the arrays--
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
np.concatenate((arr1,arr2))


array([1, 2, 3, 4, 5, 6])

In [ ]:
#dimensions and the shape of the array--
print(arr1.ndim)     #tells the dimension of the array
print(arr1.shape)       #tells the shape of the array
print(arr1.size)        #tells the total number of elements in the array


1
(3,)
3


In [ ]:
#reshpaing the array-
a = np.arange(15)
a.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
#expand dimension of the array--
#Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

a2 = a[np.newaxis,:]
a2.shape

(1, 15)

In [ ]:
#for converting array to a row vector
row_vector = a[np.newaxis, :]
row_vector.shape


(1, 15)

In [ ]:
#for converting array to a column vector--
col_vector = a[ : ,np.newaxis]
col_vector.shape

(15, 1)

In [ ]:
#we can use expand_dims to explicitily do this--
b = np.expand_dims(a,axis=1)
b.shape

(15, 1)

In [ ]:

b = np.expand_dims(a,axis=0)
b.shape

(1, 15)

In [ ]:
#que - print the indices to all the elements in the array that are less than five--
print(np.nonzero(a[a<5]))

(array([1, 2, 3, 4], dtype=int64),)


In [ ]:
#stacking of the arrays--
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
arr = np.arange(1,25).reshape(2,12)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
#to split it in three equal arrays in horizontal direction--
np.hsplit(arr,4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [ ]:
#or we can do this way-
np.split(arr,4,axis=1)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [ ]:
arr.sum(axis=0)

array([14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36])

In [ ]:
#to get unique values in the array we have --
a = np.array([1,2,3,3,2,4,5,1])
np.unique(a)

array([1, 2, 3, 4, 5])

In [ ]:
#if we want to find the indices of the unique values --
np.unique(a,return_index = True)

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 5, 6], dtype=int64))

In [ ]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
print(np.unique(a_2d))      #gives the unique values

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
print(np.unique(a_2d,axis=0))       #gives the unique rows

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#for taking transpose of a matrix--
a_2d.T

array([[ 1,  5,  9,  1],
       [ 2,  6, 10,  2],
       [ 3,  7, 11,  3],
       [ 4,  8, 12,  4]])

In [ ]:
#flip option--
#flip means reverse the order of the elements in which they occur in the array-
a_1d = np.arange(6)
reversed_a = np.flip(a_1d,axis=0)
reversed_a

array([5, 4, 3, 2, 1, 0])

In [ ]:
a_2d = np.arange(24).reshape(4,6)
a_2d


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
flipped_a = np.flip(a_2d,axis=0)
flipped_a

array([[18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [ ]:
reversed_a2d = np.flip(a_2d)
reversed_a2d

array([[23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [ ]:
#flatten and ravel--
#these two are used to flatten a multidimensional array-
a_2d.flatten()      #this returns a copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
a_2d.ravel()        #its changes are inplace doesn't return the copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])