In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.3'

In [3]:
np.__config__

<module 'numpy.__config__' from 'c:\\Users\\Dev IIT\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\__config__.py'>

In [4]:
v = np.zeros(10)
v[4]=1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [5]:
v = np.array([1,2,3,4,5])
v[::-1]

array([5, 4, 3, 2, 1])

In [6]:
v = np.arange(9)
v.resize(3,3)
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
x = np.random.rand(10,10)
x

array([[0.34534363, 0.75522029, 0.400373  , 0.55985655, 0.43696913,
        0.24868407, 0.26677008, 0.46984567, 0.71207725, 0.16731786],
       [0.14125549, 0.74234741, 0.53807025, 0.05296818, 0.57582818,
        0.41948248, 0.74987851, 0.89561779, 0.25507886, 0.67133581],
       [0.78316074, 0.35977127, 0.34658093, 0.49124685, 0.74015012,
        0.38593024, 0.69687538, 0.07193372, 0.54812804, 0.95787477],
       [0.88476126, 0.28296828, 0.15503428, 0.09646036, 0.47085429,
        0.16607786, 0.38842139, 0.18320052, 0.08726191, 0.76635412],
       [0.38601161, 0.46107109, 0.08798527, 0.34276138, 0.566599  ,
        0.88883788, 0.31474752, 0.72825552, 0.29896085, 0.85236707],
       [0.87366274, 0.56004057, 0.37399417, 0.09677742, 0.36013695,
        0.72190058, 0.02464791, 0.69728754, 0.82343912, 0.68413751],
       [0.23640351, 0.43070996, 0.23292663, 0.50395136, 0.35305163,
        0.73679139, 0.56601452, 0.1790411 , 0.62885457, 0.58785426],
       [0.83368856, 0.46544534, 0.5049145

In [9]:
print(x.min())
print(x.max())

0.007285836597795026
0.9862175826772448


In [10]:
v = np.random.rand(30)
v.mean()

0.380213673124581

In [11]:
arr1 = np.ones((5,3))
arr2 = np.ones((3,2))
# arr1 = np.matrix(ar1)
# arr2 = np.matrix(ar2)
arr1 @ arr2

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [12]:
z = np.arange(11)
z[(3<z) & (z<8)]

array([4, 5, 6, 7])

In [19]:
arr1 = np.random.rand(12)
arr2 = np.random.rand(12)
#to find the common values v/w the given 1 d arrays
print(np.intersect1d(arr1,arr2))

[]


In [14]:
arr1 = np.arange(12)
arr2 = np.arange(4,20)

print(np.intersect1d(arr1,arr2))

[ 4  5  6  7  8  9 10 11]


In [15]:
z = np.random.uniform(0,10,10)
print(np.trunc(z))

[9. 0. 1. 9. 1. 1. 2. 2. 2. 3.]


In [16]:
a = np.zeros(10)
a.flags.writeable = False
a[0]=1

ValueError: assignment destination is read-only

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[32 61 60 56]
 [48 64 48 35]
 [46 53 50 53]]
