In [2]:
import numpy as np

In [3]:
array1 = np.arange(15,41,1)
array1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40])

In [4]:
array2 = np.arange(10,25)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
even_array1 = np.arange(2,21,2)
even_array1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
even_array2 = np.arange(34,53,2)
even_array2

print(even_array2.shape,even_array1.shape)

(10,) (10,)


In [7]:
mat1 = np.stack([even_array1,even_array2],axis=0)
mat1

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [34, 36, 38, 40, 42, 44, 46, 48, 50, 52]])

In [8]:
mat2 = np.stack([even_array1,even_array2],axis=1)
mat2

array([[ 2, 34],
       [ 4, 36],
       [ 6, 38],
       [ 8, 40],
       [10, 42],
       [12, 44],
       [14, 46],
       [16, 48],
       [18, 50],
       [20, 52]])

In [9]:
mat3 = np.stack([even_array1,even_array2],axis=-1)
mat3

array([[ 2, 34],
       [ 4, 36],
       [ 6, 38],
       [ 8, 40],
       [10, 42],
       [12, 44],
       [14, 46],
       [16, 48],
       [18, 50],
       [20, 52]])

In [10]:
arr = np.arange(36)
arr.resize(6,6)
print(arr)
print(arr[2][1])
print(arr[2,1])


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
13
13


In [11]:
arr2 = np.random.rand(5,2)
print(arr2)

[[0.10703186 0.69367955]
 [0.16490975 0.23918452]
 [0.33530844 0.01101928]
 [0.61821415 0.07441109]
 [0.05092584 0.87845086]]


In [12]:
print(arr2[-1][-1])

0.8784508564270603


In [13]:
mat4 = np.matrix(arr2)
print(mat4) 

[[0.10703186 0.69367955]
 [0.16490975 0.23918452]
 [0.33530844 0.01101928]
 [0.61821415 0.07441109]
 [0.05092584 0.87845086]]


In [14]:
print(mat4.min())

0.011019284407294272


In [15]:
print(mat4.max())

0.8784508564270603


In [16]:
print(mat4.mean())

0.317313535273905


In [17]:
print(mat4.var())

0.08447210755742222


In [18]:
print(mat4.std())

0.2906408566554644
